export default function Start() {
  return (
    <>
      <svg
        width="100%"
        height="920"
        viewBox="0 0 1440 920"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          x="30%"
          y="16%"
          width="53%"
          height="64%"
          fill="#0D2748"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="47%"
          y="74%"
          width="17%"
          height="15%"
          fill="#006C7B"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="19%"
          y="-7%"
          width="67%"
          height="33%"
          fill="#006C7B"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="19%"
          y="63%"
          width="31%"
          height="37%"
          fill="#005773"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="-2%"
          y="30%"
          width="41%"
          height="57%"
          fill="#003551"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="17%"
          y="6%"
          width="31%"
          height="33%"
          fill="#005069"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="77%"
          y="39%"
          width="29%"
          height="52%"
          fill="#005E73"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="59%"
          y="55%"
          width="29%"
          height="40%"
          fill="#003D60"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="-3%"
          y="72%"
          width="12%"
          height="19%"
          fill="#008986"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="69%"
          y="-14%"
          width="32%"
          height="57%"
          fill="#007E85"
          stroke="#1E1F20"
          stroke-width="10"
        />
        <rect
          x="-3%"
          y="-7%"
          width="29%"
          height="49%"
          fill="#007B81"
          stroke="#1E1F20"
          stroke-width="10"
        />
      </svg>
    </>
  );
}
